name: CD build

on:
  workflow_run:
    workflows: ["CI build"]
    types: 
      - completed


jobs:
  deploy-to-ec2:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Pull Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

      run: sudo docker pull $DOCKERHUB_USERNAME/golden-owl-test:latest

    - name: Bring down container
      run:
        sudo docker rm -f golden-owl-test || true

    - name: Start container
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      run:
        sudo docker run -d -p 3001:3001 --name golden-owl-test $DOCKERHUB_USERNAME/golden-owl-test:latest