name: CI build

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install
        working-directory: src
        
      - name: Test
        run: |
          if npm test; then
            echo "test success"
          else
            echo "test failure"
            exit 1
          fi
        working-directory: src
      
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/golden-owl-test:latest .
          docker push $DOCKERHUB_USERNAME/golden-owl-test:latest



